### ISSUE TITLE
Fails to generate a detailed SBOM for a forked repo

### ISSUE THREAD

**Issue by anthonyharrison** [advanced-security/gh-sbom#5]
Pointing the tool at a forked repo results in an basic SBOM with none of the dependent packages identified.

**Comment by steiza** [comment]
I think what's happening here is this tool uses the Dependency Graph API, and so if you don't have Dependency Graph enabled on your repository (regardless of if it's forked or not), it won't be able get any information. I added a (hopefully) helpful error message for that case: https://github.com/advanced-security/gh-sbom/commit/781d1cee2a81550502c09aca42bbcb31c94c13cc

**Comment by anthonyharrison** [comment]
@steiza It appears that it is  possible to enable DependencyGraph for a forked repo. Maybe add this [reference](https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/configuring-the-dependency-graph) somewhere in the documentation.
